name: Run Pytest

on:
  push:
    branches: [unit-tests]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.4"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r function_app/requirements.txt
          pip install pytest==7.4.0

      - name: 'Create env file'
        run: |
          touch temp.txt
          echo AzureWebJobsStorage=${{ secrets.AzureWebJobsStorage }} > temp.txt
          echo FUNCTIONS_WORKER_RUNTIME=${{ secrets.FUNCTIONS_WORKER_RUNTIME }} > temp.txt
          echo AzureWebJobsFeatureFlags=${{ secrets.AzureWebJobsFeatureFlags }} > temp.txt
          echo BlobStorageConnectionString=${{ secrets.BlobStorageConnectionString }} > temp.txt
          echo OPENAI_KEY=${{ secrets.OPENAI_KEY }} > temp.txt
          echo FUNCTION_KEY=${{ secrets.FUNCTION_KEY }} > temp.txt
          echo CONNECTION_STRING=${{ secrets.CONNECTION_STRING }} > temp.txt
          echo STORAGE_KEY=${{ secrets.STORAGE_KEY }} > temp.txt
          echo STORAGE_URL=${{ secrets.STORAGE_URL }} > temp.txt
          echo STORAGE_CONTAINER=${{ secrets.STORAGE_CONTAINER }} > temp.txt
          echo MISTRAL_MODEL=${{ secrets.MISTRAL_MODEL }} > temp.txt
          echo MISTRAL_ENDPOINT=${{ secrets.MISTRAL_ENDPOINT }} > temp.txt
          echo MISTRAL_KEY=${{ secrets.MISTRAL_KEY }} > temp.txt
          echo LLAMA_MODEL=${{ secrets.LLAMA_MODEL }} > temp.txt
          echo LLAMA_ENDPOINT=${{ secrets.LLAMA_ENDPOINT }} > temp.txt
          echo LLAMA_KEY=${{ secrets.LLAMA_KEY }} > temp.txt
          cat temp.txt
          cp temp.txt tests/
          pwd

      - name: Run Pytest
        run: pytest --log-cli-level=INFO tests/ --junit-xml=.test_report.xml

      - name: Generate PyTest report
        uses: test-summary/action@v2
        with:
          paths: .test_report.xml
          show: fail
        if: always()