name: Run Pytest

on:
  push:
    branches: [unit-tests]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.4"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r function_app/requirements.txt
          pip install pytest==7.4.0

      - name: 'Create env file'
        run: |
          touch .env
          echo AzureWebJobsStorage=${{ secrets.AzureWebJobsStorage }} > .env
          echo FUNCTIONS_WORKER_RUNTIME=${{ secrets.FUNCTIONS_WORKER_RUNTIME }} > .env
          echo AzureWebJobsFeatureFlags=${{ secrets.AzureWebJobsFeatureFlags }} > .env
          echo BlobStorageConnectionString=${{ secrets.BlobStorageConnectionString }} > .env
          echo OPENAI_KEY=${{ secrets.OPENAI_KEY }} > .env
          echo FUNCTION_KEY=${{ secrets.FUNCTION_KEY }} > .env
          echo CONNECTION_STRING=${{ secrets.CONNECTION_STRING }} > .env
          echo STORAGE_KEY=${{ secrets.STORAGE_KEY }} > .env
          echo STORAGE_URL=${{ secrets.STORAGE_URL }} > .env
          echo STORAGE_CONTAINER=${{ secrets.STORAGE_CONTAINER }} > .env
          echo MISTRAL_MODEL=${{ secrets.MISTRAL_MODEL }} > .env
          echo MISTRAL_ENDPOINT=${{ secrets.MISTRAL_ENDPOINT }} > .env
          echo MISTRAL_KEY=${{ secrets.MISTRAL_KEY }} > .env
          echo LLAMA_MODEL=${{ secrets.LLAMA_MODEL }} > .env
          echo LLAMA_ENDPOINT=${{ secrets.LLAMA_ENDPOINT }} > .env
          echo LLAMA_KEY=${{ secrets.LLAMA_KEY }} > .env
          cat .env
          cp .env tests/.env
          pwd

      - name: Run Pytest
        run: pytest --log-cli-level=INFO tests/ --junit-xml=.test_report.xml

      - name: Generate PyTest report
        uses: test-summary/action@v2
        with:
          paths: .test_report.xml
          show: fail
        if: always()