name: Run Pytest

on:
  push:
    branches: [unit-tests]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.4"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest==7.4.0
        working-directory: function_app

      - name: Run Pytest
        run: |
          cd function_app
          pytest --log-cli-level=INFO tests/ --junit-xml=.test_report.xml

      - name: Generate PyTest report
        uses: test-summary/action@v2
        with:
          paths: .test_report.xml
          show: fail
        if: always()